import json

with open("src/answers/origin.txt", "r") as f:
    answer_list = ""
    count = 0
    for line in f:
        idiom = line.split("：")[0]
        if len(idiom) == 5 and idiom[4] == "\n":
            idiom = idiom[:4]
        if len(idiom) > 4:
            print(idiom)
        count += 1
        answer_list = answer_list + "  ['" + idiom + "'],\n"

template = """/* The code is generated by src/answers/extract.py
*  Please do not edit it manually.
*/
import { checkValidIdiom } from '~/logic'

export const answers: string[][] = [
%s
]
"""

with open("src/answers/list.ts", "w") as f:
    f.write(template % answer_list)

print("count:", count)