import json

with open("src/answers/data_source.json", "r") as f:
    data = json.load(f)

idioms = data["idioms"]
answer_list = ""
count = 0
for idiom in idioms:
    count += 1
    answer_list = answer_list + "  ['" + idiom["word"] + "'],\n"

template = """/* The code is generated by src/answers/extract.py
*  Please do not edit it manually.
*/
import { checkValidIdiom } from '~/logic'

export const answers: string[][] = [
%s
]
"""

with open("src/answers/list.ts", "w") as f:
    f.write(template % answer_list)

print("count:", count)